<h1>Understanding your data</h1>

In [1]:
import pandas as pd

<h1>Downloading a dataset from kaggle</h1>

In [2]:
!pip install kaggle
!kaggle datasets download -d hetbabariya/imdb-movies-data-collection-5000-records -p sample_data

Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (1.6.17)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2024.12.14)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from kaggle) (4.67.1)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.2.3)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle) (6.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.10)
Dataset URL: https://www.kaggle.com/datasets/hetbabariya/imdb-movies-data-collection-5000-records
License(s): CC0-1.0
Downloading imdb-movies-data-collection-5000-records.zip to sample_data
  0% 0.00/934k [00:00<?, ?B/s]
100% 934k/934k [00:00<00:00, 86.5MB/s]

In [4]:
!unzip sample_data/imdb-movies-data-collection-5000-records.zip

Archive:  sample_data/imdb-movies-data-collection-5000-records.zip
  inflating: IMDB_Movies_Dataset.csv

In [7]:
df = pd.read_csv('movies_imdb.csv')

<h1>1. How big is the data</h1>

In [8]:
df.shape

(4989, 13)

<h1>2. How does the data look like?</h1>

In [12]:
# df.head()
df.sample(5)

,Unnamed: 0,Title,Average Rating,Director,Writer,Metascore,Cast,Release Date,Country of Origin,Languages,Budget,Worldwide Gross,Runtime
3402,411,Pride and Prejudice,7.4,Robert Z. Leonard,"Aldous Huxley, Jane Murfin, Jane Austen",84.0,"Greer Garson, Laurence Olivier, Mary Boland, E...","July 26, 1940 (United States)",United States,English,NaN,"$4,030,820",1 hour 58 minutes
3134,143,Galaxy Quest,7.4,Dean Parisot,"David Howard, Robert Gordon",70.0,"Tim Allen, Sigourney Weaver, Alan Rickman, Ton...","December 25, 1999 (United States)",United States,English,"$45,000,000 (estimated)","$90,685,205",1 hour 42 minutes
3532,42,Les choses de la vie,7.4,Claude Sautet,"Sandro Continenza, Jean-Loup Dabadie, Paul Gui...",NaN,"Michel Piccoli, Romy Schneider, Gérard Lartiga...","March 13, 1970 (France)","Switzerland, France, Italy",French,NaN,"$5,063",1 hour 29 minutes
539,39,Ben-Hur,8.1,William Wyler,"Lew Wallace, Karl Tunberg, Gore Vidal",90.0,"Charlton Heston, Jack Hawkins, Stephen Boyd, H...","November 18, 1959 (Canada)",United States,English,"$15,000,000 (estimated)","$74,439,321",3 hours 32 minutes
429,429,Rascal Does Not Dream of a Dreaming Girl,8.2,Sôichi Masui,"Hajime Kamoshida, Masahiro Yokotani",NaN,"Kaito Ishikawa, Asami Seto, Inori Minase, Nao ...","June 15, 2019 (Japan)",Japan,Japanese,NaN,"$3,060,705",1 hour 29 minutes

<h1>3. What is the datatype of cols?</h1>

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4989 entries, 0 to 4988
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4989 non-null   int64
 1   Title              4989 non-null   object
 2   Average Rating     4989 non-null   float64
 3   Director           4989 non-null   object
 4   Writer             4988 non-null   object
 5   Metascore          3055 non-null   float64
 6   Cast               4982 non-null   object
 7   Release Date       4989 non-null   object
 8   Country of Origin  4986 non-null   object
 9   Languages          4968 non-null   object
 10  Budget             2651 non-null   object
 11  Worldwide Gross    3895 non-null   object
 12  Runtime            4989 non-null   object
dtypes: float64(2), int64(1), object(10)
memory usage: 506.8+ KB

<h1>4. Are there any missing values?</h1>

In [14]:
df.isnull().sum()

Unnamed: 0              0
Title                   0
Average Rating          0
Director                0
Writer                  1
Metascore            1934
Cast                    7
Release Date            0
Country of Origin       3
Languages              21
Budget               2338
Worldwide Gross      1094
Runtime                 0
dtype: int64

<h1>5. How does the data look mathematically?</h1>

In [15]:
df.describe()

        Unnamed: 0  Average Rating    Metascore
count  4989.000000     4989.000000  3055.000000
mean    248.951493        7.632892    74.684452
std     144.036753        0.365243    12.298911
min       0.000000        7.200000    25.000000
25%     124.000000        7.300000    67.000000
50%     249.000000        7.600000    76.000000
75%     374.000000        7.800000    84.000000
max     499.000000        9.300000   100.000000

<h1>6. Are there any duplicate values?</h1>

In [16]:
df.duplicated().sum()

0

<h1>7. How is the correlation between cols</h1>

In [20]:
numeric_df = df.select_dtypes(include=['number'])
numeric_df.corr()

                Unnamed: 0  Average Rating  Metascore
Unnamed: 0        1.000000       -0.117564  -0.013052
Average Rating   -0.117564        1.000000   0.342531
Metascore        -0.013052        0.342531   1.000000