<h1>Fetching data from an API</h1>

In [1]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests) (2024.12.14)

Import requests and pandas, then call the api using request.get() method

In [9]:
import requests
import pandas as pd

url = "https://api.themoviedb.org/3/movie/top_rated?api_key=f50d62d1ab0104664863698788b258cc&page=2"

response = requests.get(url)

data = response.json()['results']

Convert the response into data frame

In [14]:
pd.DataFrame(data)[['id','title','original_title','overview','popularity','release_date','adult','vote_average']]

,id,title,original_title,overview,popularity,release_date,adult,vote_average
0,637,Life Is Beautiful,La vita è bella,A touching story of an Italian book seller of ...,57.714,1997-12-20,False,8.450
1,157336,Interstellar,Interstellar,The adventures of a group of explorers who mak...,232.815,2014-11-05,False,8.445
2,550,Fight Club,Fight Club,A ticking-time-bomb insomniac and a slippery s...,110.059,1999-10-15,False,8.438
3,667257,Impossible Things,Cosas imposibles,"After the death of her abusive husband, Matild...",14.609,2021-06-17,False,8.434
4,539,Psycho,Psycho,When larcenous real estate clerk Marion Crane ...,44.608,1960-06-22,False,8.428
5,598,City of God,Cidade de Deus,In the poverty-stricken favelas of Rio de Jane...,41.188,2002-08-30,False,8.426
6,40096,A Dog's Will,O Auto da Compadecida,The lively João Grilo and the sly Chicó are po...,15.733,2000-09-15,False,8.400
7,311,Once Upon a Time in America,Once Upon a Time in America,A former Prohibition-era Jewish gangster retur...,50.506,1984-05-23,False,8.419
8,120,The Lord of the Rings: The Fellowship of the Ring,The Lord of the Rings: The Fellowship of the Ring,"Young hobbit Frodo Baggins, after inheriting a...",141.566,2001-12-18,False,8.416
9,510,One Flew Over the Cuckoo's Nest,One Flew Over the Cuckoo's Nest,A petty criminal fakes insanity to serve his s...,39.250,1975-11-19,False,8.415
10,696374,Gabriel's Inferno,Gabriel's Inferno,An intriguing and sinful exploration of seduct...,12.005,2020-05-29,False,8.400
11,14537,Harakiri,切腹,Down-on-his-luck veteran Tsugumo Hanshirō ente...,17.880,1962-09-15,False,8.404
12,704264,Primal: Tales of Savagery,Primal: Tales of Savagery,Genndy Tartakovsky's Primal: Tales of Savagery...,12.429,2019-11-21,False,8.403
13,4935,Howl's Moving Castle,ハウルの動く城,"Sophie, a young milliner, is turned into an el...",71.258,2004-09-09,False,8.403
14,324857,Spider-Man: Into the Spider-Verse,Spider-Man: Into the Spider-Verse,Struggling to find his place in the world whil...,111.267,2018-12-06,False,8.399
15,121,The Lord of the Rings: The Two Towers,The Lord of the Rings: The Two Towers,Frodo Baggins and the other members of the Fel...,101.073,2002-12-18,False,8.399
16,1891,The Empire Strikes Back,The Empire Strikes Back,"The epic saga continues as Luke Skywalker, in ...",50.116,1980-05-20,False,8.400
17,724089,Gabriel's Inferno: Part II,Gabriel's Inferno: Part II,Professor Gabriel Emerson finally learns the t...,9.171,2020-07-31,False,8.389
18,1184918,The Wild Robot,The Wild Robot,"After a shipwreck, an intelligent robot called...",978.986,2024-09-08,False,8.386
19,378064,A Silent Voice: The Movie,映画 聲の形,Shouya Ishida starts bullying the new girl in ...,53.628,2016-09-17,False,8.400

Using loop to fetch data from multiple pages of the url

In [17]:
df = pd.DataFrame()

In [23]:
for i in range (1,100):
  response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=f50d62d1ab0104664863698788b258cc&page={}'.format(i))
  temp = pd.DataFrame(response.json()['results'])[['id','title','original_title','overview','popularity','release_date','adult','vote_average']]
  df = pd.concat([df , temp],ignore_index=True)

In [24]:
df

,id,title,original_title,overview,popularity,release_date,adult,vote_average
0,278,The Shawshank Redemption,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,163.526,1994-09-23,False,8.708
1,238,The Godfather,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",190.973,1972-03-14,False,8.690
2,240,The Godfather Part II,The Godfather Part II,In the continuing saga of the Corleone crime f...,107.211,1974-12-20,False,8.572
3,424,Schindler's List,Schindler's List,The true story of how businessman Oskar Schind...,93.651,1993-12-15,False,8.566
4,389,12 Angry Men,12 Angry Men,The defense and the prosecution have rested an...,66.631,1957-04-10,False,8.546
...,...,...,...,...,...,...,...,...
1975,9385,The Twelve Tasks of Asterix,Les 12 travaux d'Astérix,Asterix and Obelix depart on an adventure to c...,20.664,1976-06-26,False,7.319
1976,687,Dead Man Walking,Dead Man Walking,A death row inmate turns for spiritual guidanc...,14.584,1995-12-29,False,7.319
1977,46919,Daisies,Sedmikrásky,Two teenage girls embark on a series of destru...,10.913,1966-12-30,False,7.300
1978,7340,Carrie,Carrie,Withdrawn and sensitive teen Carrie White face...,24.215,1976-11-03,False,7.300
1979,438148,Minions: The Rise of Gru,Minions: The Rise of Gru,A fanboy of a supervillain supergroup known as...,87.953,2022-06-29,False,7.300

In [26]:
df.shape

(1980, 8)

Now we can convert this data into csv using to_csv method

In [27]:
df.to_csv('movies.csv')