<h1>One Hot Encoding</h1>

In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('cars.csv')
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

<h2>One hot encoding using pandas</h2>

In [9]:
# df['brand'].value_counts()
df['brand'].nunique()

32

In [10]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [11]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [16]:
df2 = pd.get_dummies(df , columns=['fuel' , 'owner'] )
df2

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [14]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   brand                       8128 non-null   object
 1   km_driven                   8128 non-null   int64
 2   selling_price               8128 non-null   int64
 3   fuel_CNG                    8128 non-null   bool
 4   fuel_Diesel                 8128 non-null   bool
 5   fuel_LPG                    8128 non-null   bool
 6   fuel_Petrol                 8128 non-null   bool
 7   owner_First Owner           8128 non-null   bool
 8   owner_Fourth & Above Owner  8128 non-null   bool
 9   owner_Second Owner          8128 non-null   bool
 10  owner_Test Drive Car        8128 non-null   bool
 11  owner_Third Owner           8128 non-null   bool
dtypes: bool(9), int64(2), object(1)
memory usage: 262.1+ KB

<h2>k-1 one Hot encoding</h2>

In [15]:
df2 = pd.get_dummies(df , columns=['fuel' , 'owner'] , drop_first=True)
df2

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [17]:
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(df.drop('selling_price' , axis = 1) , df['selling_price'] , test_size=0.3 , random_state=0)

In [18]:
X_train.shape

(5689, 4)

In [19]:
from sklearn.preprocessing import OneHotEncoder

In [34]:
ohe = OneHotEncoder(drop='first', sparse_output=False)

In [35]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [36]:
X_test_new = ohe.fit_transform(X_test[['fuel','owner']])

In [37]:
np.hstack((X_train[['brand','km_driven']].values , X_train_new)).shape

(5689, 9)

<h2>OHE with top categories</h2>

In [40]:
counts = df['brand'].value_counts()

In [41]:
threesold = 100

In [42]:
repl = counts[counts <= threesold].index

In [47]:
pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(10)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
6599,False,False,False,False,False,False,False,False,True,False,False,False,False
5908,False,False,False,False,False,False,True,False,False,False,False,False,False
1329,False,False,False,False,False,False,True,False,False,False,False,False,False
5914,False,False,False,False,False,False,False,False,False,False,False,True,False
1459,False,False,False,False,False,False,True,False,False,False,False,False,False
7678,False,False,False,False,False,False,True,False,False,False,False,False,False
6604,False,False,False,False,False,True,False,False,False,False,False,False,False
3114,False,False,False,False,True,False,False,False,False,False,False,False,False
739,False,False,False,False,False,False,False,False,False,False,False,True,False
6552,False,False,False,False,False,False,False,False,False,False,False,False,True